### ISSUE TITLE
I have some issue when build project

### ISSUE THREAD

**Issue by Kroberus** [yellowmessenger/cordova-plugin-ymchat#24]
I use cordova-android: 10.1.2
When building project it said cannot find symbol
please support me. Thank you!
@sankalp211 @sukrit-ym 
![Image Pasted at 2023-3-28 13-55](https://user-images.githubusercontent.com/118706956/228419489-2d77ac88-8a90-4696-889f-4e56a5373186.png)

**Comment by sukrit-ym** [comment]
Hi, we will check this.

**Comment by sankalp211** [comment]
@Kroberus Can you help us with the SDK version information you are using.

**Comment by Kroberus** [comment]
> @Kroberus Can you help us with the SDK version information you are using.

I use sdk version: 30.0.1 anh 30.0.3. it not working
Thank you!

**Comment by sankalp211** [comment]
@Kroberus The issue has been resolved, please update [cordova-plugin-ymchat](https://www.npmjs.com/package/cordova-plugin-ymchat) to the latest(**_v.2.3.2_**)
